version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: juniorsntsid/airflow-docker:v2
        # image: juniorsntsid/airflow:v2
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - LOAD_EX=n
            - EXECUTOR=Kubernetes
            - AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY=Never
            - AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM=airflow-dags
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__KUBERNETES__IN_CLUSTER=False
            - AIRFLOW__KUBERNETES__CONFIG_FILE=/usr/local/airflow/config
            - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
            - AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE=False
            # - AIRFLOW__CORE__WORKER_SERVICE_ACCOUNT_NAME=admin
            - 'AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS={ "_request_timeout": 50 }'
            # - "AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS={_request_timeout: 50}"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - /home/juniordev/.kube/config:/usr/local/airflow/config
            # - ./airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        links:
          - postgres
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        image: juniorsntsid/airflow-docker:v2
        # image: juniorsntsid/airflow:v2
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - /home/juniordev/.kube/config:/usr/local/airflow/config
            # - ./airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Kubernetes
            - AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY=Never
            # - AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM=airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__KUBERNETES__IN_CLUSTER=False
            - AIRFLOW__KUBERNETES__CONFIG_FILE=/usr/local/airflow/config
            - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
            - AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE=False
            # - AIRFLOW__CORE__WORKER_SERVICE_ACCOUNT_NAME=admin
            - 'AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS={ "_request_timeout": "50" }'
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler